name: Sync

on: workflow_dispatch

jobs:
  sync:
    name: Sync from swsnr/turnon
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: "curl -sSfL https://codeberg.org/swsnr/turnon/raw/branch/main/flatpak/de.swsnr.turnon.yaml > de.swsnr.turnon.yaml"
      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Update from swsnr/turnon"
          branch: swsnr/turnon/update
          delete-branch: true
          base: master
          sign-commits: true
          title: Update manifest from upstream
          body: |
            Update flatpak manifest from [swsnr/turnon](https://codeberg.org/swsnr/turnon).

            PR created by [sync workflow](https://github.com/flathub/de.swsnr.turnon/actions/workflows/sync.yaml)
          assignees: swsnr
